### ISSUE TITLE
Detail on the target_markers.fa input

### ISSUE THREAD

**Issue by NicolasNesi** [chutter/PHYLOCAP#1]
Hello,

Thank you very much for your pipeline. I am interested to test it and compare results with others tools (e.g. hybpiper, secapr).

I have a question about the target_markers.fa file to use. 

What do you recommend, the seqs must be the baitsprobs seqs (for me 90 bp) or the sequences of the CDS (used to design the probes baits) is ok? (In you FrogCap folder you have both baits and markers). 
What is the format for the fasta header: >RefGenome_CDSGenename

Thanks for the help,

regards

Nicolas

**Comment by chutter** [comment]
Hi Nicolas, 

The target_markers.fa file should be the sequences of the CDS used to design the baits, as this file will be used for other things as well. I tried de novo assembling bait files and that can be problematic with lots of things not assembling, misassembles, and baits that were cut out of the process for whatever reason causing errors. The format of the fasta header can be whatever you like just do not put a "_|_" (underscore pipe underscore) in there as that is used during alignment to separate species and locus name. Also spaces are bad generally. So your RefGenome_CDSGenename will work great!

Thanks for the question and I'll update the documentation to include this info. 

Best,

Carl

**Comment by NicolasNesi** [comment]
Hi Carl,
Thank you very much for your answer. To let you know, for the first step, workflow-1_preprocess.R you could make some update:
- the conda yaml to a more recent version of r-biomartr (got this error https://github.com/ropensci/biomartr/issues/92)
- update genbank_accesion in decontamination_database.csv for Human (GCA_000001405.29), Pseudonocardia(GCA_000196675.2), and Ralstonia (other sp GCA_003595305.1). Biomartr with the option used can't download the human mitochondrion NC_012920.1.

Thanks,
Best
Nicolas
